apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: Emissary
metadata:
  name: emissary
  namespace: example-env
spec:
  clusterName: example-cluster

  labels:
    team: platform

  crds:
    enabled: true
    namespace: emissary

  ingress:
    enabled: true
    namespace: emissary
    values:
      replicaCount: 2
      service:
        type: LoadBalancer
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 512Mi
